import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  {
    slug: "050-karat-pirlanta-tektas-yuzuk",
    code: "YA-TK-001",
    name: "0,50 Karat Pirlanta Tektas Yuzuk",
    description: "14 ayar sari altin uzerine 0.50 karat pirlanta tasli zarif tektas yuzuk.",
    about: "0,50 Karat Pirlanta Tektas Yuzuk, pirlantalarin en saf halini yansitan ozel bir tasarimdir.",
    price: 45000,
    oldPrice: 52000,
    category: "yuzuk",
    categoryLabel: "Yuzuk",
    material: "14 Ayar Sari Altin",
    weight: "2.80 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([{ type: "Pirlanta", count: 1, carat: 0.50, color: "F/G", clarity: "VS1", shape: "Yuvarlak" }]),
    images: JSON.stringify(["/images/yuzuk-1-main.jpg", "/images/yuzuk-1-back.jpg", "/images/yuzuk-1-side.jpg"]),
    hoverImage: "/images/yüzük1-1.png",
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: true,
    inStock: true,
    order: 1,
  },
  {
    slug: "030-karat-pirlanta-kolye",
    code: "YA-KL-001",
    name: "0,30 Karat Pirlanta Kolye",
    description: "18 ayar beyaz altin zincir uzerinde 0.30 karat pirlanta tasli minimalist kolye.",
    about: "0,30 Karat Pirlanta Kolye, sadeligin ve zarafetin mukemmel birlesimi.",
    price: 28000,
    oldPrice: 32000,
    category: "kolye",
    categoryLabel: "Kolye",
    material: "18 Ayar Beyaz Altin",
    weight: "3.20 gr",
    purity: "18 Ayar",
    stones: JSON.stringify([{ type: "Pirlanta", count: 1, carat: 0.30, color: "F/G", clarity: "VS2", shape: "Yuvarlak" }]),
    images: JSON.stringify(["/images/kolye-1.png"]),
    hoverImage: "/images/kolye1-1.png",
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: true, images: [] },
      { color: "gold", label: "Sari Altin", available: false, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "white",
    featured: true,
    inStock: true,
    order: 2,
  },
  {
    slug: "040-karat-pirlanta-kupe",
    code: "YA-KP-001",
    name: "0,40 Karat Pirlanta Kupe",
    description: "14 ayar sari altin uzerine toplam 0.40 karat pirlanta tasli kupe cifti.",
    about: "0,40 Karat Pirlanta Kupe, klasik ve zarif tasarimi ile her kombinle uyum saglar.",
    price: 18500,
    oldPrice: 22000,
    category: "kupe",
    categoryLabel: "Kupe",
    material: "14 Ayar Sari Altin",
    weight: "2.10 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([{ type: "Pirlanta", count: 2, carat: 0.40, color: "G/H", clarity: "VS2", shape: "Yuvarlak" }]),
    images: JSON.stringify(["/images/kupe-1.png"]),
    hoverImage: "/images/küpe1-1.png",
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: true,
    inStock: true,
    order: 3,
  },
  {
    slug: "zumrut-tasli-el-isi-yuzuk",
    code: "YA-TK-002",
    name: "Zumrut Tasli El Isi Yuzuk",
    description: "14 ayar altin uzerine dogal zumrut tasli el isi yuzuk.",
    about: "Zumrut Tasli El Isi Yuzuk, geleneksel Turk kuyumculuk sanatinin modern bir yorumu.",
    price: 35000,
    oldPrice: 42000,
    category: "yuzuk",
    categoryLabel: "Yuzuk",
    material: "14 Ayar Altin",
    weight: "3.60 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([
      { type: "Zumrut", count: 1, carat: 0.80, color: "Yesil", clarity: "Dogal", shape: "Oval" },
      { type: "Pirlanta", count: 12, carat: 0.15, color: "F/G", clarity: "SI", shape: "Yuvarlak" }
    ]),
    images: JSON.stringify(["/images/ring-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: false,
    inStock: true,
    order: 4,
  },
  {
    slug: "tatli-su-incisi-kolye",
    code: "YA-KL-002",
    name: "Tatli Su Incisi Kolye",
    description: "Gercek tatli su incileri ile hazirlanmis zarif kolye.",
    about: "Tatli Su Incisi Kolye, dogal guzelligi en saf haliyle sunar.",
    price: 8500,
    category: "kolye",
    categoryLabel: "Kolye",
    material: "925 Ayar Gumus",
    weight: "28.00 gr",
    purity: "925 Ayar",
    stones: JSON.stringify([{ type: "Tatli Su Incisi", count: 45, carat: 0, color: "Beyaz", clarity: "AAA", shape: "Yuvarlak" }]),
    images: JSON.stringify(["/images/necklace-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: true, images: [] },
      { color: "gold", label: "Sari Altin", available: false, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "white",
    featured: false,
    inStock: true,
    order: 5,
  },
  {
    slug: "14-ayar-altin-kelepce-bileklik",
    code: "YA-BL-001",
    name: "14 Ayar Altin Kelepce Bileklik",
    description: "14 ayar altin modern kelepce bileklik. Ayarlanabilir boyut.",
    about: "14 Ayar Altin Kelepce Bileklik, modern cizgileri ile dikkat ceker.",
    price: 22000,
    oldPrice: 26000,
    category: "bileklik",
    categoryLabel: "Bileklik",
    material: "14 Ayar Altin",
    weight: "8.20 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([]),
    images: JSON.stringify(["/images/bileklik-1.png"]),
    hoverImage: "/images/bileklik1-1.png",
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: true,
    inStock: true,
    order: 6,
  },
  {
    slug: "040-karat-pirlanta-kupe-beyaz",
    code: "YA-KP-002",
    name: "0,40 Karat Pirlanta Kupe",
    description: "18 ayar beyaz altin uzerine toplam 0.40 karat pirlanta tasli kupe cifti.",
    about: "0,40 Karat Pirlanta Kupe, her iki kulaginizda toplam 0.40 karat pirlanta ile goz kamastirici.",
    price: 32000,
    oldPrice: 38000,
    category: "kupe",
    categoryLabel: "Kupe",
    material: "18 Ayar Beyaz Altin",
    weight: "2.40 gr",
    purity: "18 Ayar",
    stones: JSON.stringify([{ type: "Pirlanta", count: 2, carat: 0.40, color: "F/G", clarity: "VS1", shape: "Yuvarlak" }]),
    images: JSON.stringify(["/images/earring-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: true, images: [] },
      { color: "gold", label: "Sari Altin", available: false, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "white",
    featured: false,
    inStock: true,
    order: 7,
  },
  {
    slug: "klasik-alyans-seti",
    code: "YA-TK-003",
    name: "Klasik Alyans Seti",
    description: "14 ayar altin klasik alyans seti. Ozel gunleriniz icin.",
    about: "Klasik Alyans Seti, evliliginizin simgesi olacak zamansiz bir tasarim.",
    price: 18000,
    category: "yuzuk",
    categoryLabel: "Yuzuk",
    material: "14 Ayar Altin",
    weight: "6.00 gr (cift)",
    purity: "14 Ayar",
    stones: JSON.stringify([]),
    images: JSON.stringify(["/images/ring-3.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: false,
    inStock: true,
    order: 8,
  },
  {
    slug: "015-karat-pirlanta-bestas-yuzuk",
    code: "YA-TK-004",
    name: "0,15 Karat Pirlanta Bestas Yuzuk",
    description: "8 ayar beyaz altin uzerine 5 adet pirlanta tasli bestas yuzuk.",
    about: "0,15 Karat Pirlanta Bestas Yuzuk, pirlantin goz aliciligi ile harmanlanan cok ozel bir yuzuk.",
    price: 12990,
    oldPrice: 28900,
    category: "yuzuk",
    categoryLabel: "Yuzuk",
    material: "8 Ayar Beyaz Altin",
    weight: "1.40 gr",
    purity: "8 Ayar",
    stones: JSON.stringify([{ type: "Pirlanta", count: 5, carat: 0.15, color: "F/G", clarity: "SI", shape: "Yuvarlak" }]),
    images: JSON.stringify(["/images/ring-4.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: true, images: [] },
      { color: "gold", label: "Sari Altin", available: false, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "white",
    featured: true,
    inStock: true,
    order: 9,
  },
  {
    slug: "14-ayar-altin-erkek-alyans",
    code: "YA-AL-001",
    name: "14 Ayar Altin Erkek Alyans",
    description: "14 ayar sari altin klasik erkek alyans. Sade ve zarif tasarim.",
    about: "14 Ayar Altin Erkek Alyans, zamansiz elegansini modern cizgilerle bulusturan ozel bir parca.",
    price: 8500,
    oldPrice: 14500,
    category: "yuzuk",
    categoryLabel: "Alyans",
    material: "14 Ayar Sari Altin",
    weight: "4.50 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([]),
    images: JSON.stringify(["/images/erkek-alyans-1.png", "/images/erkek-alyans-2.png", "/images/erkek-alyans-3.png"]),
    hoverImage: "/images/erkek-alyans-hover.jpg",
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: true,
    inStock: true,
    order: 10,
  },
  {
    slug: "14-ayar-altin-kadin-alyans",
    code: "YA-AL-002",
    name: "14 Ayar Altin Kadin Alyans",
    description: "14 ayar sari altin ince ve zarif kadin alyans. Minimalist tasarim.",
    about: "14 Ayar Altin Kadin Alyans, incelik ve zarafetin simgesi.",
    price: 5500,
    oldPrice: 9500,
    category: "yuzuk",
    categoryLabel: "Alyans",
    material: "14 Ayar Sari Altin",
    weight: "2.20 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([]),
    images: JSON.stringify(["/images/kadin-alyans-1.png", "/images/kadin-alyans-2.png", "/images/kadin-alyans-3.jpg"]),
    hoverImage: "/images/kadin-alyans-hover.jpg",
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: true,
    inStock: true,
    order: 11,
  },
  {
    slug: "melek-kanadi-pirlanta-kolye",
    code: "YA-KL-003",
    name: "Melek Kanadi Pirlanta Kolye",
    description: "18 ayar beyaz altin uzerine pirlanta tasli melek kanadi motifli zarif kolye.",
    about: "Melek Kanadi Pirlanta Kolye, kanat detaylari uzerinde isiyan pirlantalarla goz kamastirici.",
    price: 32000,
    oldPrice: 38000,
    category: "kolye",
    categoryLabel: "Kolye",
    material: "18 Ayar Beyaz Altin",
    weight: "3.80 gr",
    purity: "18 Ayar",
    stones: JSON.stringify([{ type: "Pirlanta", count: 28, carat: 0.35, color: "F/G", clarity: "VS1", shape: "Yuvarlak" }]),
    images: JSON.stringify(["/images/kolye-melek-kanadi-1.jpg", "/images/kolye-melek-kanadi-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: true, images: ["/images/kolye-melek-kanadi-1.jpg", "/images/kolye-melek-kanadi-2.jpg"] },
      { color: "gold", label: "Sari Altin", available: true, images: ["/images/kolye-melek-kanadi-gold-2.jpg", "/images/kolye-melek-kanadi-gold-1.jpg"] },
      { color: "rose", label: "Rose Gold", available: true, images: ["/images/kolye-melek-kanadi-rose-1.jpg", "/images/kolye-melek-kanadi-rose-2.jpg"] },
    ]),
    defaultColor: "white",
    featured: true,
    inStock: true,
    order: 12,
  },
  {
    slug: "uclu-yonca-sedef-kolye",
    code: "YA-KL-004",
    name: "Uclu Yonca Sedef Kolye",
    description: "18 ayar beyaz altin uzerine sedef tasli uc yoncali minimalist kolye.",
    about: "Uclu Yonca Sedef Kolye, dogal sedefin isiltisi ile zarif bir gorunum sunar.",
    price: 18500,
    oldPrice: 22000,
    category: "kolye",
    categoryLabel: "Kolye",
    material: "18 Ayar Beyaz Altin",
    weight: "4.20 gr",
    purity: "18 Ayar",
    stones: JSON.stringify([{ type: "Sedef", count: 3, carat: 0, color: "Beyaz", clarity: "AAA", shape: "Yonca" }]),
    images: JSON.stringify(["/images/kolye-yonca-1.jpg", "/images/kolye-yonca-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: true, images: [] },
      { color: "gold", label: "Sari Altin", available: false, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "white",
    featured: true,
    inStock: true,
    order: 13,
  },
  {
    slug: "armut-kesim-pirlanta-kolye",
    code: "YA-KL-005",
    name: "Armut Kesim Pirlanta Kolye",
    description: "14 ayar sari altin uzerine armut kesim pirlanta tasli tektas kolye.",
    about: "Armut Kesim Pirlanta Kolye, klasik armut kesimin zarafetini modern bir tasarimla bulusturur.",
    price: 42000,
    oldPrice: 48000,
    category: "kolye",
    categoryLabel: "Kolye",
    material: "14 Ayar Sari Altin",
    weight: "2.90 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([{ type: "Pirlanta", count: 1, carat: 0.50, color: "F/G", clarity: "VS1", shape: "Armut" }]),
    images: JSON.stringify(["/images/kolye-armut-1.jpg", "/images/kolye-armut-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: true,
    inStock: true,
    order: 14,
  },
  {
    slug: "baguette-kesim-pirlanta-kolye",
    code: "YA-KL-006",
    name: "Baguette Kesim Pirlanta Kolye",
    description: "14 ayar sari altin uzerine baguette kesim pirlanta tasli modern kolye.",
    about: "Baguette Kesim Pirlanta Kolye, dikdortgen kesimin keskin hatlari ile cagdas bir gorunum sunar.",
    price: 28000,
    oldPrice: 32000,
    category: "kolye",
    categoryLabel: "Kolye",
    material: "14 Ayar Sari Altin",
    weight: "3.10 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([{ type: "Pirlanta", count: 1, carat: 0.40, color: "F/G", clarity: "VS2", shape: "Baguette" }]),
    images: JSON.stringify(["/images/kolye-baguette-1.jpg", "/images/kolye-baguette-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: false,
    inStock: true,
    order: 15,
  },
  {
    slug: "ikili-ucgen-sarkitli-kolye",
    code: "YA-KL-007",
    name: "Ikili Ucgen Sarkitli Kolye",
    description: "14 ayar sari altin ikili ucgen sarkitli modern lariat kolye.",
    about: "Ikili Ucgen Sarkitli Kolye, geometrik cizgileri ile dikkat ceken modern bir tasarim.",
    price: 15500,
    oldPrice: 18000,
    category: "kolye",
    categoryLabel: "Kolye",
    material: "14 Ayar Sari Altin",
    weight: "3.50 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([]),
    images: JSON.stringify(["/images/kolye-ucgen-1.jpg", "/images/kolye-ucgen-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: false,
    inStock: true,
    order: 16,
  },
  {
    slug: "damla-formlu-altin-kolye",
    code: "YA-KL-008",
    name: "Damla Formlu Altin Kolye",
    description: "14 ayar sari altin damla formlu minimalist kolye.",
    about: "Damla Formlu Altin Kolye, sade ve zarif tasarimi ile her tarza uyum saglar.",
    price: 12000,
    oldPrice: 14500,
    category: "kolye",
    categoryLabel: "Kolye",
    material: "14 Ayar Sari Altin",
    weight: "2.40 gr",
    purity: "14 Ayar",
    stones: JSON.stringify([]),
    images: JSON.stringify(["/images/kolye-damla-1.jpg", "/images/kolye-damla-2.jpg"]),
    colorVariants: JSON.stringify([
      { color: "white", label: "Beyaz Altin", available: false, images: [] },
      { color: "gold", label: "Sari Altin", available: true, images: [] },
      { color: "rose", label: "Rose Gold", available: false, images: [] },
    ]),
    defaultColor: "gold",
    featured: false,
    inStock: true,
    order: 17,
  },
];

async function main() {
  console.log('Migrating products to database...');

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
    console.log(`  ✓ ${product.name}`);
  }

  console.log(`\nDone! ${products.length} products migrated.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
